# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16b583a90310c47ba4185cd01180db3d5277305d8ed90875c0eacd07878666acf8b81547aaba87fb2a641b168a435eb1b25cbb498fd5b5096d848c62d66978a8

test:
  secret_key_base: 6ae9bef7f9cd68edcb9949be9f00f8fb4fd6245aa332e6d8101eab20fbbd50e20bf5471930ffb219bd6cf011484366be3f0b76e29aeb70707781e598c5129b5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
